---
- name: Revoking of client certificate
  import_tasks: revoke.yml

- name: Include OVPN group_vars
  include_vars: 
    dir: "{{ inventory_dir }}/group_vars/openvpn"
    extensions:
      - yml
      - yaml

- name: Configure OpenVPN with new CRL list
  import_tasks: transfer_crl.yml
  delegate_to: ovpn