---
- name: revoke |> Revoke client certificate
  no_log: true
  expect:
    command: ./easyrsa revoke "{{ client_name | mandatory }}"
    responses:
      (.*)Enter pass phrase for(.*): "{{ ca_password }}"
    chdir: "{{ easyrsa_path }}"

- name: revoke |> Generate new CRL
  expect:
    command: ./easyrsa gen-crl
    responses:
      (.*)Enter pass phrase for(.*): "{{ ca_password }}"
    chdir: "{{ easyrsa_path }}"