FROM centos:8

# update system
RUN yum update -y \
 && yum clean all

# install necessary packages
RUN yum install -y sudo openssh-server openssh-clients \
    python3 ca-certificates

# create user used for ssh'ing
RUN useradd -m -G wheel -s /bin/bash docker \
 && echo "docker:rekcod" | chpasswd

# setup ssh with authorized_keys
RUN mkdir /home/docker/.ssh
COPY tests/id_rsa.pub /home/docker/.ssh/authorized_keys
RUN chown -R docker:docker /home/docker/.ssh/ && \
    chmod 701 /home/docker && \
    chmod 700 /home/docker/.ssh && \
    chmod 600 /home/docker/.ssh/authorized_keys

# expose port 22 for ssh
EXPOSE 22

CMD ["/usr/sbin/init"]