- name: generate-password |> Generate random CA password
  no_log: yes
  shell: head /dev/urandom | tr -dc a-zA-Z0-9 | head -c 15
  register: ca_password_result

- name: generate-password |> Save generated CA password
  no_log: yes
  lineinfile:
    line: "ca_password: {{ ca_password_result.stdout }}"
    path: "{{ inventory_dir }}/group_vars/certauth/vault.yml"
    create: yes
  delegate_to: localhost

- name: generate-password |> Set CA password fact
  no_log: yes
  set_fact:
    ca_password: "{{ ca_password_result.stdout }}"