---
- name: sign-certificate |> Pull OVPN certificate from OVPN server
  synchronize:
    src: "{{ easyrsa_path }}/pki/reqs/{{ openvpn_common_name }}.req"
    dest: /tmp
    mode: pull

- name: sign-certificate |> Import OVPN certificate
  command: ./easyrsa import-req "/tmp/{{ openvpn_common_name }}.req" "{{ openvpn_common_name }}"
  args:
    chdir: "{{ easyrsa_path }}"
    creates: "{{ ca_ovpn_req }}"

- name: sign-certificate |> Sign OVPN certificate
  no_log: true
  expect:
    command: ./easyrsa sign-req server "{{ openvpn_common_name }}"
    responses:
      (.*)Enter pass phrase for(.*): "{{ ca_password }}"
    chdir: "{{ easyrsa_path }}"
    creates: "{{ ca_ovpn_issued_crt }}"

- name: sign-certificate |> Push OVPN certificate to OVPN server
  synchronize:
    src: "{{ ca_ovpn_issued_crt }}"
    dest: /tmp
    mode: push

- name: sign-certificate |> Push CA certificate to OVPN server
  synchronize:
    src: "{{ ca_crt }}"
    dest: /tmp
    mode: push

- name: sign-certificate |> Push CRL to OVPN server
  synchronize:
    src: "{{ ca_crl }}"
    dest: /tmp
    mode: push